fukumotom/WorkManager

WorkManager/src/main/webapp/WEB-INF/jsp/header.jsp, WorkManager/src/main/webapp/WEB-INF/jsp/menu.jsp, WorkManager/src/main/webapp/WEB-INF/jsp/user/userRegistConfirm.jsp, WorkManager/src/main/webapp/WEB-INF/jsp/user/userRegistForm.jsp, WorkManager/src/main/webapp/WEB-INF/jsp/work/workEditForm.jsp, WorkManager/src/main/webapp/WEB-INF/jsp/work/workList.jsp, WorkManager/src/main/webapp/WEB-INF/jsp/work/workRegistForm.jsp, WorkManager/src/main/webapp/WEB-INF/login.jsp
=> modify that input tag close

WorkManager/src/main/java/jp/kigami/ojt/db/util/CommonDbUtil.java
=> modify map diamond operator

WorkManager/src/main/java/jp/kigami/ojt/common/util/ConstantDef.java
=> Create constant definition

WorkManager/src/main/java/jp/kigami/ojt/form/WorkRegisterForm.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkRegister.java, WorkManager/src/main/webapp/WEB-INF/jsp/work/workRegistForm.jsp
WorkRegisterFormの作成
画面表示情報をformでやり取りするように修正
=> modify request attribute

WorkManager/src/main/webapp/WEB-INF/web.xml
web.xmlの例外クラスのパッケージを修正
不要なsampleコードを削除
=> delete unneed sample and fix exception-type

WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkRegister.java
=> 例外の塗りつぶしを解消

WorkManager/src/main/java/jp/kigami/ojt/common/util/MsgCodeDef.java, WorkManager/src/main/java/jp/kigami/ojt/common/util/PropertyUtils.java, WorkManager/src/main/resources/messages.properties
=> modify propertyUtil and messageDef and message.properties

WorkManager/src/main/java/jp/kigami/ojt/servlet/UserRegistServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkEditServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkRegistServlet.java
=> #74 modify servlet name

WorkManager/src/main/java/jp/kigami/ojt/common/exception/SystemException.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/LogoutServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/MenuServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/UserRegistServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkEditServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkListServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkRegistServlet.java
=> fix exception handling #87

WorkManager/src/main/webapp/WEB-INF/jsp/menu.jsp
ログインユーザ名の表示をEL式を使用した方法に修正しました。　#89
=> modify el #89

WorkManager/src/main/java/jp/kigami/ojt/db/util/CommonDbUtil.java
=> fix warning coment #85

WorkManager/src/main/java/jp/kigami/ojt/common/util/ConstantDef.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/MenuServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkListServlet.java
=> constants of the attribute

WorkManager/src/main/java/jp/kigami/ojt/dao/UserRegisterDao.java, WorkManager/src/main/java/jp/kigami/ojt/dao/WorkDao.java, WorkManager/src/main/java/jp/kigami/ojt/dao/dto/WorkDto.java, WorkManager/src/main/java/jp/kigami/ojt/db/util/CommonDbUtil.java, WorkManager/src/main/java/jp/kigami/ojt/model/Work.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/UserRegistServlet.java, WorkManager/src/main/java/jp/kigami/ojt/servlet/WorkListServlet.java
=> modify_dbutil #85

WorkManager/src/main/java/jp/kigami/ojt/filter/CharasetFilter.java, WorkManager/src/main/java/jp/kigami/ojt/listener/InitialListener.java
#106 FilterとListenerのパッケージを変更しました。
=> change the package configuration of filter and listener #106

WorkManager/src/main/java/jp/kigami/ojt/common/util/ConstantDef.java, WorkManager/src/main/java/jp/kigami/ojt/common/util/PropertyUtils.java, WorkManager/src/main/java/jp/kigami/ojt/db/util/CommonDbUtil.java, WorkManager/src/main/resources/db.properties
#110 db.propertiesにlookupするJNDI名の定義を移動しました。
=> move jndi name to properties #110

WorkManager/src/main/java/jp/co/alpha/kgmwmr/dao/WorkDao.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/db/util/CommonDbUtil.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/logic/UserRegistLogic.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/logic/WorkLogic.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/servlet/WorkRegistServlet.java, WorkManager/src/main/resources/sql/getSelectWork.sql
=> addtion transaction manage #107

WorkManager/pom.xml
=> Issue#120/addtion profile

WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/exception/BindFormatException.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/exception/BusinessException.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/exception/IllegalOperationException.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/exception/SystemException.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/util/ConvertToModelUtils.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/util/DateUtils.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/util/EncryptionUtils.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/util/InputValidation.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/util/ValidationResult.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/dao/UserRegisterDao.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/dao/WorkDao.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/db/util/CommonDbUtil.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/filter/CharasetFilter.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/listener/InitialListener.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/logic/UserRegistLogic.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/logic/WorkLogic.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/servlet/LogoutServlet.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/servlet/MenuServlet.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/servlet/WorkEditServlet.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/servlet/WorkListServlet.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/servlet/WorkRegistServlet.java
=> add or modify javadoc

WorkManager/src/main/java/jp/co/alpha/kgmwmr/logic/WorkLogic.java
TODOコメントを削除
フォーム使用箇所の見直し
メソッドを不必要に分けていたのをまとめました。
=> delete todo and modify transaction method #104

WorkManager/src/main/java/jp/co/alpha/kgmwmr/common/util/ThreadIdentifier.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/db/util/CommonDbUtil.java
スレッドIDの取得をThreadlocalを使うように修正しました。
（スレッド名も必要でしょうか？）
=> use thread local #126

WorkManager/src/main/java/jp/co/alpha/kgmwmr/dao/WorkDao.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/form/WorkEditForm.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/form/WorkRegisterViewForm.java, WorkManager/src/main/java/jp/co/alpha/kgmwmr/logic/WorkLogic.java, WorkManager/src/main/resources/sql/getContentsList.sql, WorkManager/src/main/resources/sql/getNoteList.sql, WorkManager/src/main/webapp/WEB-INF/jsp/work/workEditForm.jsp, WorkManager/src/main/webapp/WEB-INF/jsp/work/workRegistForm.jsp
作業登録画面、作業編集画面の作業内容と備考にコンボボックスを適用しました。
=> create combo box #34

WorkManager/src/main/webapp/WEB-INF/jsp/work/workList.jsp
=> fix button view when delete list #133
